//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class BronPc
    {
        public int idBronPc { get; set; }
        public string NumberTable { get; set; }
        public Nullable<int> idUsers { get; set; }
        public Nullable<int> idPc { get; set; }
    
        public virtual Pc Pc { get; set; }
        public virtual Users Users { get; set; }
    }
}
